=== oscarbravovillada/UD3.-Ampliaci-UDT-Exercicis/ejercicio1lote.dtd
<!ELEMENT listaentrega (lote+)>
<!ELEMENT lote (pale+)>
<!ELEMENT pale (contenido+, numcajas, peso, manipulacion)>
<!ELEMENT contenido (nombrecomponente, procedencia* ,numeroseriecomponente,pesocomponente,unidaddepeso?)>
<!ELEMENT nombrecomponente (#PCDATA)>
<!ELEMENT procedencia (#PCDATA)>
<!ELEMENT numeroseriecomponente (#PCDATA)>
<!ELEMENT pesocomponente (#PCDATA)>
<!ELEMENT unidaddepeso (#PCDATA)>
<!ELEMENT numcajas (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT manipulacion (#PCDATA)>

=== oscarbravovillada/UD3.-Ampliaci-UDT-Exercicis/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaentrega SYSTEM "ejercicio1lote.dtd">
<listaentrega>
	<lote>
		<pale>
			<contenido>
				<nombrecomponente>Asus pc</nombrecomponente>
				<procedencia>Colombia</procedencia>
				<numeroseriecomponente>1215</numeroseriecomponente>
				<pesocomponente>2kg</pesocomponente>
				<unidaddepeso>1.5kg</unidaddepeso>
			</contenido>
			<numcajas>5</numcajas>
			<peso>5kg</peso>
			<manipulacion></manipulacion>
		</pale>
		<pale>
			<contenido>
				<nombrecomponente>Asus pc</nombrecomponente>
				<procedencia>Espa√±a</procedencia>
				<numeroseriecomponente>1215</numeroseriecomponente>
				<pesocomponente>2kg</pesocomponente>
				<unidaddepeso>1.5kg</unidaddepeso>
			</contenido>
			<numcajas>5</numcajas>
			<peso>5kg</peso>
			<manipulacion></manipulacion>
		</pale>
	</lote>
	<lote>
		<pale>
			<contenido>
				<nombrecomponente>Asus pc</nombrecomponente>
				<procedencia></procedencia>
				<numeroseriecomponente>1215</numeroseriecomponente>
				<pesocomponente>2kg</pesocomponente>
				<unidaddepeso>1.5kg</unidaddepeso>
			</contenido>
			<numcajas>5</numcajas>
			<peso>5kg</peso>
			<manipulacion></manipulacion>
		</pale>
	</lote>
</listaentrega>
